version: '3.4'

services:

    postgres:
        image: postgres:13.4
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin            
        logging:
          options:
            max-size: 10m
            max-file: "3"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - postgres-network
            
networks:
    postgres-network:
        driver: bridge

volumes:
    postgres_data:    
        driver: local
